---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/ubuntu/trusty"
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/ubuntu/precise"
- name: debian-7.8
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/debian/7"
- name: centos-7.0
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/rhel/7"
- name: centos-6.6
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/rhel/6"
- name: centos-5.11
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/rhel/5"
- name: fedora-19
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/fedora/19"
  provisioner:
    root_path: /home/vagrant/kitchen
- name: freebsd-10.1
  driver:
    guest: ":freebsd"
    vagrantfile_erb: vagrantfile_bsd.erb
  run_list:
  - recipe[freebsd::portsnap]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/freebsd/10"
- name: freebsd-9.2
  driver:
    guest: ":freebsd"
    vagrantfile_erb: vagrantfile_bsd.erb
  run_list:
  - recipe[freebsd::portsnap]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/freebsd/9.2"
suites:
- name: default
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: "2"
          minor: "1"
          incremental: "1"
- name: search
  run_list:
  - recipe[riak]
  attributes:
    riak:
      manage_java: true
      package:
        version:
          major: "2"
          minor: "1"
          incremental: "1"
      config:
        search.top_level: "on"
  excludes: ["freebsd-10.1", "freebsd-9.2"]
- name: enterprise
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: "2"
          minor: "1"
          incremental: "1"
        local:
          url: ""
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: custom_package
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_package"
- name: source
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "source"
      source:
        major: "2"
        minor: "1"
        incremental: "1"
