---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "3f29736ab0dc8b094272d9caefed4e795ae293f54f79bed8d0464ca821c865ef"
- name: debian-7.1.0
  driver_config:
    box: opscode-debian-7.1.0
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          debian:
            "7": "7badc4cf084d3a84bbc3c25e206648216e5262d268ea647c438411822c7ae77a"
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list:
  - recipe[yum::epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "a2234d09bdbf08da8b9bf5627b4ea718772fc4964c4d59bd3d4c8ada83d5a9f1"
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 512
  run_list:
  - recipe[yum::epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "5": "d75f0a548b586b327186aba93943aabec0fb51f5ea2acf48de8a5d0a26fea9d7"
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes: {}
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 3
          incremental: 2
- name: default12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 2
          incremental: 1
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 3
          incremental: 2
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 2
          incremental: 1
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: source
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes: {}
- name: source13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          minor: 3
          incremental: 2
- name: source12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          minor: 2
          incremental: 1
