<%
version = '2.1.1'
split = version.split('.')
maj = split[0]
min = split[1]
inc = split[2]
url = "http://s3.amazonaws.com/downloads.basho.com/riak/#{maj}.#{min}"
%>
---
driver:
  name: vagrant
  require_chef_omnibus: 12.6.0
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/ubuntu/trusty"
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/ubuntu/precise"
- name: debian-7.8
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/debian/7"
- name: centos-7.1
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/rhel/7"
- name: centos-6.6
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/rhel/6"
- name: centos-5.11
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/rhel/5"
- name: freebsd-10.1
  driver:
    guest: ":freebsd"
    vagrantfile_erb: vagrantfile_bsd.erb
  run_list:
  - recipe[freebsd::portsnap]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/freebsd/10"
- name: freebsd-9.3
  driver:
    guest: ":freebsd"
    vagrantfile_erb: vagrantfile_bsd.erb
  run_list:
  - recipe[freebsd::portsnap]
  attributes:
    riak:
      package:
        local:
          url: "<%= url %>/<%= version %>/freebsd/9.2"
suites:
- name: default
  run_list:
  - recipe[riak::sysctl]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: <%= maj %>
          minor: <%= min %>
          incremental: <%= inc %>
- name: search
  run_list:
  - recipe[riak::sysctl]
  - recipe[riak]
  attributes:
    riak:
      manage_java: true
      package:
        version:
          major: <%= maj %>
          minor: <%= min %>
          incremental: <%= inc %>
      config:
        search.top_level: "on"
  excludes: ["freebsd-10.1", "freebsd-9.3"]
- name: enterprise
  run_list:
  - recipe[riak::sysctl]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: <%= maj %>
          minor: <%= min %>
          incremental: <%= inc %>
        local:
          url: ""
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: custom_package
  run_list:
  - recipe[riak::sysctl]
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_package"
- name: source
  run_list:
  - recipe[riak::sysctl]
  - recipe[riak]
  attributes:
    riak:
      install_method: "source"
      source:
        major: <%= maj %>
        minor: <%= min %>
        incremental: <%= inc %>
  excludes: ["freebsd-10.1", "freebsd-9.3"]
- name: sysctl
  run_list:
    - recipe[riak::sysctl]
  excludes: ["freebsd-10.1", "freebsd-9.3"]
