---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list:
  - recipe[riak]
  attributes: {}
- name: source
  run_list:
  - recipe[riak::source]
  attributes: {}
