---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: "11.6.0"
    chef_omnibus_url: https://gist.github.com/hectcastro/6443633/raw/install.sh
    # Requires a patched version of kitchen-vagrant:
    # https://github.com/hectcastro/kitchen-vagrant/compare/hc-cachier
    use_cachier_plugin: true
    customize:
      memory: 512
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "b4e4e31b8e1cd25ea4d3bcd9af94e7322ce1c08645425891574f57ba58f8c516"
- name: debian-7.1.0
  driver_config:
    box: opscode-debian-7.1.0
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
    require_chef_omnibus: "11.6.0"
    chef_omnibus_url: https://gist.github.com/hectcastro/6443633/raw/install.sh
    # Requires a patched version of kitchen-vagrant:
    # https://github.com/hectcastro/kitchen-vagrant/compare/hc-cachier
    use_cachier_plugin: true
    customize:
      memory: 512
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          debian:
            "7": "ab5b07c9430aed4874020aa8c4688f1efa14f2a8fba5659fbcbf2004183b51fc"
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
    require_chef_omnibus: "11.6.0"
    chef_omnibus_url: https://gist.github.com/hectcastro/6443633/raw/install.sh
    # Requires a patched version of kitchen-vagrant:
    # https://github.com/hectcastro/kitchen-vagrant/compare/hc-cachier
    use_cachier_plugin: true
    customize:
      memory: 512
  run_list:
  - recipe[yum::epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "5bfed85a02df7f297cf20402f147997b06c8ea59dbe860186a54e9dec2dc26e2"
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
    require_chef_omnibus: "11.6.0"
    chef_omnibus_url: https://gist.github.com/hectcastro/6443633/raw/install.sh
    # Requires a patched version of kitchen-vagrant:
    # https://github.com/hectcastro/kitchen-vagrant/compare/hc-cachier
    use_cachier_plugin: true
    customize:
      memory: 512
  run_list:
  - recipe[yum::epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "5": "c821ddea30cdce72464909ea0a6dd2bb9e0dada4041e2b56e3569bad11a5f869"
suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes: {}
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 3
          incremental: 2
- name: default12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 2
          incremental: 1
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 3
          incremental: 3
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          minor: 2
          incremental: 1
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: custom_repository
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_repository"
- name: source
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes: {}
- name: source13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          minor: 3
          incremental: 2
- name: source12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          minor: 2
          incremental: 1
