---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 512

provisioner:
  name: chef_solo
  root_path: /home/vagrant/kitchen

platforms:
- name: ubuntu-13.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "280c816e5dc4a83e3bc5e82d011fed4b3fb83098b81df2997aa17462261c86e6"
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          ubuntu:
            precise: "280c816e5dc4a83e3bc5e82d011fed4b3fb83098b81df2997aa17462261c86e6"
- name: debian-7.2.0
  run_list:
  - recipe[apt]
  attributes:
    riak:
      package:
        checksum:
          debian:
            "7": "ddc35ba5de39bb31a5f4d1b39627ac6b859dc176ff8a6890d95fb32b3f560589"
- name: centos-6.5
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "6": "2cf9f2481409d2871a6d453a9287f317bd4f5c1cb2e49432f4fee0ac106af56c"
- name: centos-5.10
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        checksum:
          centos:
            "5": "3e6ea55c08c0e0c5d92195955275faed082d0b42fa8bde36e485bbf10b98cae7"

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
- name: default13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 3
          incremental: 2
- name: default12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 2
          incremental: 1
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 3
          incremental: 3
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: enterprise12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 2
          incremental: 1
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: custom_repository
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_repository"
- name: custom_repository_enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        name: "riak-ee"
      install_method: "custom_repository"
- name: source
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes: {}
- name: source13
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          major: 1
          minor: 3
          incremental: 2
- name: source12
  run_list:
  - recipe[minitest-handler]
  - recipe[riak::source]
  attributes:
    riak:
      source:
        version:
          major: 1
          minor: 2
          incremental: 1
